FROM php:8.4-apache

RUN docker-php-ext-install pdo_mysql

WORKDIR /var/www/html

COPY backend-api/ ./api/
COPY classes/ ./classes/

RUN mkdir -p uploads/conteineres \
    && chown -R www-data:www-data uploads

EXPOSE 80