-- Esquema PostgreSQL para aplicar no SQL Editor do Supabase.
-- Cria as tabelas sem apagar dados existentes.

CREATE TABLE IF NOT EXISTS public.locador (
    nm_email_locador VARCHAR(150) PRIMARY KEY,
    cd_cnpj_locador VARCHAR(14) NOT NULL UNIQUE,
    nm_locador VARCHAR(150) NOT NULL,
    nm_senha_locador VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.status_manutencao (
    cd_status_manutencao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_status_manutencao VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS public.tipo_movimentacao (
    cd_tipo_movimentacao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_tipo_movimentacao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.locatario (
    nm_email_locatario VARCHAR(150) PRIMARY KEY,
    nm_senha_locatario VARCHAR(150) NOT NULL,
    nm_locatario VARCHAR(150) NOT NULL,
    cd_cpf_cnpj_locatario VARCHAR(14) UNIQUE
);

CREATE TABLE IF NOT EXISTS public.tamanho_conteiner (
    cd_tamanho_conteiner INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_tamanho_conteiner VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tipo_conteiner (
    cd_tipo_conteiner INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_tipo_conteiner VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.modelo_conteiner (
    cd_tipo_conteiner INTEGER NOT NULL REFERENCES public.tipo_conteiner (cd_tipo_conteiner),
    cd_tamanho_conteiner INTEGER NOT NULL REFERENCES public.tamanho_conteiner (cd_tamanho_conteiner),
    qt_tara_modelo_conteiner DECIMAL(8,2),
    qt_carga_maxima_modelo_conteiner DECIMAL(8,2),
    PRIMARY KEY (cd_tipo_conteiner, cd_tamanho_conteiner)
);

CREATE TABLE IF NOT EXISTS public.fabricante (
    cd_cnpj_fabricante VARCHAR(14) PRIMARY KEY,
    nm_fabricante VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.deposito (
    cd_deposito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_deposito VARCHAR(150),
    cd_cep_deposito VARCHAR(9) NOT NULL,
    nm_endereco_deposito VARCHAR(150) NOT NULL,
    qt_raio_atuacao_deposito DECIMAL(8,2) NOT NULL,
    qt_latitude_deposito DECIMAL(8,6) NOT NULL,
    qt_longitude_deposito DECIMAL(9,6) NOT NULL,
    qt_maxima_conteineres_deposito INTEGER,
    qt_atual_conteineres_deposito INTEGER,
    nm_email_locador VARCHAR(150) NOT NULL REFERENCES public.locador (nm_email_locador)
);

CREATE TABLE IF NOT EXISTS public.conteiner (
    cd_conteiner INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_fabricacao_conteiner DATE NOT NULL,
    cd_bic_conteiner VARCHAR(11) NOT NULL,
    qt_tara_conteiner DECIMAL(8,2) NOT NULL,
    qt_carga_maxima_conteiner DECIMAL(8,2) NOT NULL,
    cd_tipo_conteiner INTEGER NOT NULL REFERENCES public.tipo_conteiner (cd_tipo_conteiner),
    cd_tamanho_conteiner INTEGER NOT NULL REFERENCES public.tamanho_conteiner (cd_tamanho_conteiner),
    cd_deposito INTEGER REFERENCES public.deposito (cd_deposito),
    cd_cnpj_fabricante VARCHAR(14) REFERENCES public.fabricante (cd_cnpj_fabricante),
    nm_email_locador VARCHAR(150) NOT NULL REFERENCES public.locador (nm_email_locador)
);

CREATE TABLE IF NOT EXISTS public.categoria_componente (
    cd_categoria_componente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_categoria_componente VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.componente (
    cd_componente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_componente VARCHAR(150) NOT NULL,
    vl_componente DECIMAL(8,2) NOT NULL,
    qt_vida_util_componente INTEGER NOT NULL,
    dt_instalacao_componente TIMESTAMP NOT NULL,
    cd_conteiner INTEGER NOT NULL REFERENCES public.conteiner (cd_conteiner),
    cd_categoria_componente INTEGER NOT NULL REFERENCES public.categoria_componente (cd_categoria_componente)
);

CREATE TABLE IF NOT EXISTS public.finalidade (
    cd_finalidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_finalidade VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.finalidade_conteiner (
    cd_conteiner INTEGER NOT NULL REFERENCES public.conteiner (cd_conteiner),
    cd_finalidade INTEGER NOT NULL REFERENCES public.finalidade (cd_finalidade),
    PRIMARY KEY (cd_conteiner, cd_finalidade)
);

CREATE TABLE IF NOT EXISTS public.tipo_status (
    cd_tipo_status INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_tipo_status VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.status (
    cd_status INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_status VARCHAR(150) NOT NULL,
    cd_tipo_status INTEGER REFERENCES public.tipo_status (cd_tipo_status)
);

CREATE TABLE IF NOT EXISTS public.status_conteiner (
    cd_conteiner INTEGER NOT NULL REFERENCES public.conteiner (cd_conteiner),
    cd_status INTEGER NOT NULL REFERENCES public.status (cd_status),
    PRIMARY KEY (cd_conteiner, cd_status)
);

CREATE TABLE IF NOT EXISTS public.tipo_aluguel (
    cd_tipo_aluguel INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_tipo_aluguel VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tipo_aluguel_conteiner (
    cd_conteiner INTEGER NOT NULL REFERENCES public.conteiner (cd_conteiner),
    cd_tipo_aluguel INTEGER NOT NULL REFERENCES public.tipo_aluguel (cd_tipo_aluguel),
    pc_multa_tipo_aluguel_conteiner DECIMAL(5,2),
    vl_tipo_aluguel_conteiner DECIMAL(10,2),
    PRIMARY KEY (cd_conteiner, cd_tipo_aluguel)
);

CREATE TABLE IF NOT EXISTS public.tipo_manutencao (
    cd_tipo_manutencao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_tipo_manutencao VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.manutencao (
    cd_conteiner INTEGER NOT NULL REFERENCES public.conteiner (cd_conteiner),
    dt_inicio_manutencao TIMESTAMP NOT NULL,
    vl_manutencao DECIMAL(10,2) NOT NULL,
    cd_tipo_manutencao INTEGER NOT NULL REFERENCES public.tipo_manutencao (cd_tipo_manutencao),
    cd_status_manutencao INTEGER NOT NULL REFERENCES public.status_manutencao (cd_status_manutencao),
    dt_termino_manutencao TIMESTAMP,
    PRIMARY KEY (cd_conteiner, dt_inicio_manutencao)
);

CREATE TABLE IF NOT EXISTS public.tipo_vistoria (
    cd_tipo_vistoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_tipo_vistoria VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.vistoria (
    dt_inicio_vistoria TIMESTAMP NOT NULL,
    dt_termino_vistoria TIMESTAMP,
    cd_conteiner INTEGER NOT NULL REFERENCES public.conteiner (cd_conteiner),
    cd_tipo_vistoria INTEGER NOT NULL REFERENCES public.tipo_vistoria (cd_tipo_vistoria),
    cd_deposito INTEGER REFERENCES public.deposito (cd_deposito),
    PRIMARY KEY (cd_conteiner, dt_inicio_vistoria)
);

CREATE TABLE IF NOT EXISTS public.item_vistoria (
    cd_item_vistoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_item_vistoria VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.resposta_item_vistoria (
    cd_conteiner INTEGER NOT NULL,
    dt_inicio_vistoria TIMESTAMP NOT NULL,
    cd_item_vistoria INTEGER NOT NULL REFERENCES public.item_vistoria (cd_item_vistoria),
    ic_resposta SMALLINT NOT NULL,
    PRIMARY KEY (cd_conteiner, dt_inicio_vistoria, cd_item_vistoria),
    FOREIGN KEY (cd_conteiner, dt_inicio_vistoria)
        REFERENCES public.vistoria (cd_conteiner, dt_inicio_vistoria)
);

CREATE TABLE IF NOT EXISTS public.endereco_entrega (
    cd_endereco_entrega INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_endereco_entrega VARCHAR(100) NOT NULL,
    cd_cep_endereco_entrega VARCHAR(9),
    ds_complemento TEXT,
    nm_email_locatario VARCHAR(150) NOT NULL REFERENCES public.locatario (nm_email_locatario)
);

CREATE TABLE IF NOT EXISTS public.contrato_aluguel (
    cd_endereco_entrega INTEGER REFERENCES public.endereco_entrega (cd_endereco_entrega),
    nm_email_locatario VARCHAR(150) NOT NULL REFERENCES public.locatario (nm_email_locatario),
    cd_conteiner INTEGER NOT NULL REFERENCES public.conteiner (cd_conteiner),
    nm_endereco_retorno VARCHAR(150),
    dt_entrega DATE,
    dt_retorno DATE,
    qt_duracao_contrato_aluguel INTEGER,
    cd_tipo_aluguel INTEGER REFERENCES public.tipo_aluguel (cd_tipo_aluguel),
    dt_criacao_contrato_aluguel TIMESTAMP NOT NULL,
    PRIMARY KEY (nm_email_locatario, cd_conteiner, dt_criacao_contrato_aluguel)
);

CREATE TABLE IF NOT EXISTS public.parcela_aluguel (
    dt_abertura_parcela_aluguel DATE NOT NULL,
    nm_email_locatario VARCHAR(150) NOT NULL,
    cd_conteiner INTEGER NOT NULL,
    dt_criacao_contrato_aluguel TIMESTAMP NOT NULL,
    ic_parcela_aluguel_paga SMALLINT,
    dt_vencimento_parcela_aluguel DATE,
    vl_parcela_aluguel DECIMAL(7,2),
    dt_pagamento_parcela_aluguel DATE,
    PRIMARY KEY (
        nm_email_locatario,
        cd_conteiner,
        dt_criacao_contrato_aluguel,
        dt_abertura_parcela_aluguel
    ),
    FOREIGN KEY (nm_email_locatario, cd_conteiner, dt_criacao_contrato_aluguel)
        REFERENCES public.contrato_aluguel (
            nm_email_locatario,
            cd_conteiner,
            dt_criacao_contrato_aluguel
        )
);

CREATE TABLE IF NOT EXISTS public.movimentacao (
    cd_deposito INTEGER,
    nm_email_locatario VARCHAR(150),
    cd_conteiner INTEGER,
    dt_criacao_contrato_aluguel TIMESTAMP,
    cd_tipo_movimentacao INTEGER REFERENCES public.tipo_movimentacao (cd_tipo_movimentacao),
    PRIMARY KEY (
        cd_deposito,
        nm_email_locatario,
        cd_conteiner,
        dt_criacao_contrato_aluguel,
        cd_tipo_movimentacao
    ),
    FOREIGN KEY (nm_email_locatario, cd_conteiner, dt_criacao_contrato_aluguel)
        REFERENCES public.contrato_aluguel (
            nm_email_locatario,
            cd_conteiner,
            dt_criacao_contrato_aluguel
        )
);

CREATE TABLE IF NOT EXISTS public.moduleasy_sessions (
    session_id VARCHAR(128) PRIMARY KEY,
    session_data BYTEA NOT NULL,
    expires_at BIGINT NOT NULL
);

-- As chamadas feitas pelo backend PHP usam a chave secreta no servidor e,
-- por isso, podem operar nessas tabelas sem políticas para clientes públicos.
DO $$
DECLARE
    nome_tabela TEXT;
BEGIN
    FOREACH nome_tabela IN ARRAY ARRAY[
        'locador', 'status_manutencao', 'tipo_movimentacao', 'locatario',
        'tamanho_conteiner', 'tipo_conteiner', 'modelo_conteiner', 'fabricante',
        'deposito', 'conteiner', 'categoria_componente', 'componente', 'finalidade',
        'finalidade_conteiner', 'tipo_status', 'status', 'status_conteiner',
        'tipo_aluguel', 'tipo_aluguel_conteiner', 'tipo_manutencao', 'manutencao',
        'tipo_vistoria', 'vistoria', 'item_vistoria', 'resposta_item_vistoria',
        'endereco_entrega', 'contrato_aluguel', 'parcela_aluguel', 'movimentacao',
        'moduleasy_sessions'
    ]
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', nome_tabela);
    END LOOP;
END
$$;
